# update
#2.0
# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 6
  selector:
    matchLabels:
      app: springboot-app
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: acrk8s123.azurecr.io/bprasanna881/ravidineshspring:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
    volumes:
    - name: test-volume
      persistentVolumeClaim:
        claimName: azure-managed-disk  
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/azure-disk
parameters:
  skuName: Standard_LRS
---
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
  name: azure-managed-disk
  spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 5Gi
---
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app
